language: r
r:
  - release
  - devel
cache: packages

r_github_packages:
  - r-lib/covr

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'
warnings_are_errors: true

env:
- _R_CHECK_FORCE_SUGGESTS_=false NOT_CRAN=true MAKEFLAGS=-j2

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

after_success:
  - Rscript -e 'covr::codecov()'
